import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DF0pOnKmv0tw&quantity=1000&networkId=1&serviceTypeId=1&serviceId=157044&isDripFeed=false&dripFeedQuantityStep=1&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=&quantity=1000&networkId=1&serviceTypeId=1&serviceId=157044&isDripFeed=false&dripFeedQuantityStep=1&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=&quantity=100&networkId=1&serviceTypeId=1&serviceId=157044&isDripFeed=false&dripFeedQuantityStep=1&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=&quantity=100&networkId=1&serviceTypeId=4&serviceId=157044&isDripFeed=false&dripFeedQuantityStep=1&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=&quantity=100&networkId=1&serviceTypeId=4&serviceId=142418&isDripFeed=false&dripFeedQuantityStep=1&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=&quantity=100&networkId=1&serviceTypeId=4&serviceId=142418&isDripFeed=false&dripFeedQuantityStep=100&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DF0pOnKmv0tw&quantity=100&networkId=1&serviceTypeId=4&serviceId=142418&isDripFeed=false&dripFeedQuantityStep=100&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DF0pOnKmv0tw&quantity=1000&networkId=1&serviceTypeId=4&serviceId=142418&isDripFeed=false&dripFeedQuantityStep=100&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DF0pOnKmv0tw&quantity=1000&networkId=1&serviceTypeId=1&serviceId=142418&isDripFeed=false&dripFeedQuantityStep=100&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DF0pOnKmv0tw&quantity=1000&networkId=1&serviceTypeId=1&serviceId=157044&isDripFeed=false&dripFeedQuantityStep=100&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DF0pOnKmv0tw&quantity=1000&networkId=1&serviceTypeId=1&serviceId=157044&isDripFeed=false&dripFeedQuantityStep=1&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.getByRole('button', { name: 'Accept all' }).click();
  await page.getByRole('button', { name: 'Buy in one click' }).click();
  await page.getByRole('banner').locator('div').filter({ hasText: 'Light mode USD ($) Create order 0' }).getByRole('link').click();
  await page.getByLabel('E-mail').fill('TestUser@test.com');
  await page.getByLabel('E-mail').press('Tab');
  await page.getByLabel('Password').fill('TestUser');
  await page.getByLabel('Password').press('Enter');
  await page.goto('https://smmpanelka.com/app/');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DF0pOnKmv0tw&quantity=1000&networkId=1&serviceTypeId=1&serviceId=157044&isDripFeed=false&dripFeedQuantityStep=1&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=&quantity=1000&networkId=1&serviceTypeId=1&serviceId=157044&isDripFeed=false&dripFeedQuantityStep=1&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=&quantity=100&networkId=1&serviceTypeId=1&serviceId=157044&isDripFeed=false&dripFeedQuantityStep=1&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=&quantity=100&networkId=1&serviceTypeId=4&serviceId=157044&isDripFeed=false&dripFeedQuantityStep=1&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=&quantity=100&networkId=1&serviceTypeId=4&serviceId=142418&isDripFeed=false&dripFeedQuantityStep=1&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=&quantity=100&networkId=1&serviceTypeId=4&serviceId=142418&isDripFeed=false&dripFeedQuantityStep=100&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DF0pOnKmv0tw&quantity=100&networkId=1&serviceTypeId=4&serviceId=142418&isDripFeed=false&dripFeedQuantityStep=100&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DF0pOnKmv0tw&quantity=1000&networkId=1&serviceTypeId=4&serviceId=142418&isDripFeed=false&dripFeedQuantityStep=100&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DF0pOnKmv0tw&quantity=1000&networkId=1&serviceTypeId=1&serviceId=142418&isDripFeed=false&dripFeedQuantityStep=100&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DF0pOnKmv0tw&quantity=1000&networkId=1&serviceTypeId=1&serviceId=157044&isDripFeed=false&dripFeedQuantityStep=100&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.goto('https://smmpanelka.com/app/orders/create?serviceSlug&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DF0pOnKmv0tw&quantity=1000&networkId=1&serviceTypeId=1&serviceId=157044&isDripFeed=false&dripFeedQuantityStep=1&numberOfRuns=2&dripFeedMode=flat&dripFeedMinutes=60&type=single');
  await page.getByRole('button', { name: 'Buy in one click' }).click();
  await page.getByRole('button', { name: 'RUB' }).click();
  await page.getByText('Perfect Money').click();
  await page.getByRole('button', { name: 'BUY FOR $' }).click();
  await expect(page.getByRole('heading', { name: 'Perfect Money' })).toBeVisible();
});